services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    volumes:
      - ./user-service:/app

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    volumes:
      - ./order-service:/app

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway:/app
    depends_on:
      - user-service
      - order-service
